name: runnest
description: RUNNE$T - Your Personal Running Tracker

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  camera: ^0.10.5+5
  permission_handler: ^11.1.0
  path_provider: ^2.1.1
  uuid: ^4.2.1
  shared_preferences: ^2.2.2
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/run.jpg"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/run.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/